### PR TITLE
add LC_ALL=C to fix i18n issues with shell cmd line, fix mislabeling of devices

### PR DESCRIPTION
**Pull request by hzulla**
This might fix KanoComputing/kano-burners#28

### CODE REVIEW

**Comment by hzulla** [comment]
2nd commit might also fix KanoComputing/kano-burners#29

**Comment by hzulla** [comment]
Well, [one should use LC_ALL, not LANG](http://permalink.gmane.org/gmane.comp.internationalization.linux/4822), so here it is.

**Comment by hzulla** [comment]
Bump.

**Comment by hzulla** [comment]
Bump.

**Comment by hzulla** [comment]
@alex5imon requesting review. Thanks.

**Comment by tombettany** [comment]
@hzulla This looks good. We are currently testing https://github.com/KanoComputing/kano-burners/pull/36 which we think will fix critical issue https://github.com/KanoComputing/kano-burners/issues/32 so that is the priority right now; it is a very large PR and merging this now might cause some awkward conflicts so do you mind if we put this one on hold until that is finalised?

**Comment by hzulla** [comment]
No, not at all. Thanks.

**Comment by hzulla** [comment]
In response to @alex5imon 's mail:

The GUI isn't translated in this patch. However, the LC_ALL is still necessairy, as kano-burners will parse the output of `parted` from the command line and will fail when the response is in locale-aware format.

**Comment by Ealdwulf** [comment]
I have merged this in to our development branch. Thanks very much for these @hzulla !

**Pull request closed without merging**
